add error handling via email for attachment upload
qbicsoftware/etl-scripts pull request #111
Opened 2023-03-15 16:40 UTC by wow-such-code

- uses provided user name and uni host to send error mails
- no LDAP support, yet
- mails useful information on 3 known error cases to the user
- mails original error message in other error cases
- if email cannot be sent, logs this
- throws original error message after attempting to send email

2023-03-16 10:08 UTC, Steffengreiner requested changes
Heya @wow-such-code , Overall very nice work! 
I have some suggestions on how to improve the code readability, however the only blocking thing imo is on how the mail properties are stored and accessed within this class. Once that is resolved i'll happily approve it 🏅

2023-03-16 10:08 UTC, Steffengreiner commented on drop-boxes/register-attachments-dropbox/register-attachment-dropbox.py
> +MAIL_FROM = "notification_service@qbis.qbic.uni-tuebingen.de"
This should be moved into environment variables or a seperate property file if possible (I see e.g. that there is a plugin property file already within the same directory).  
Otherwise we'd have to redeploy the script if these values change.

2023-03-16 10:08 UTC, Steffengreiner commented on drop-boxes/register-attachments-dropbox/register-attachment-dropbox.py
> +	text += "Please see the openBIS log for the original error message.\n"
The email itself could be composed in a seperate EmailFactory method similiar like we do it in the data-manager-application. This would allow us to extend it in the future more easily :)

2023-03-16 10:08 UTC, Steffengreiner commented on drop-boxes/register-attachments-dropbox/register-attachment-dropbox.py
> +		project = code[:5]
NIT: Extracting the projectCode from the Barcode could be done in a seperate method to better highlight and adapt the procedure if necessary. 
Another possibility would be to define a global variable like PROJECTPREFIX which stores the end number(5) of this range.

2023-03-16 10:08 UTC, Steffengreiner commented on drop-boxes/register-attachments-dropbox/register-attachment-dropbox.py
> +	pass
NIT: NoSamplesFoundForProjectException would make more sense for this exceptions purpose

2023-03-16 10:08 UTC, Steffengreiner commented on drop-boxes/register-attachments-dropbox/register-attachment-dropbox.py
> +			infoSampleID = "/"+space+"/"+code+"000"
This could also be moved into a seperate method(e.g. generateSampleID()) instead of hardcoding it here.

2023-03-16 10:08 UTC, Steffengreiner commented on drop-boxes/register-attachments-dropbox/register-attachment-dropbox.py
> +				experimentID = '/' + space + '/' + project + '/'+ project+'_INFO'
This could also be moved into a seperate method(e.g. generateExperimentId()) instead of hardcoding it here.

2023-03-16 10:08 UTC, Steffengreiner commented on drop-boxes/register-attachments-dropbox/register-attachment-dropbox.py
> +			sc.addMatchClause(SearchCriteria.MatchClause.createAttributeMatch(SearchCriteria.MatchClauseAttribute.CODE, project+"ENTITY-1"))
What's the purpose of adding the "Entity-1" string here? Could this be done via a global or at least local Variable which explains the context?

2023-03-16 10:08 UTC, Steffengreiner commented on drop-boxes/register-attachments-dropbox/register-attachment-dropbox.py
> +				sa = transaction.createNewSample(infoSampleID, "Q_ATTACHMENT_SAMPLE")
NIT: All of these openBis hardcoded lines could also be provided via an Enum with a key explaining their purpose and a value containing the openBis terminology.

2023-03-16 10:08 UTC, Steffengreiner commented on drop-boxes/register-attachments-dropbox/register-attachment-dropbox.py
> +	smtpServer.close()
Since we don't want to have a seperate class, could the email logic be moved to an inner class within this python script?(if that's possible in python, i'm not sure 🤷 ). This would help distuingish it from the registration code

2023-03-16 14:16 UTC, wow-such-code commented on drop-boxes/register-attachments-dropbox/register-attachment-dropbox.py
> +				sa = transaction.createNewSample(infoSampleID, "Q_ATTACHMENT_SAMPLE")
good point, but this is a larger project IMHO

2023-03-16 14:18 UTC, wow-such-code commented on drop-boxes/register-attachments-dropbox/register-attachment-dropbox.py
> +			sc.addMatchClause(SearchCriteria.MatchClause.createAttributeMatch(SearchCriteria.MatchClauseAttribute.CODE, project+"ENTITY-1"))
The thought here is that this is the first sample that is registered in a project so it is likely the first that can be found. finding one sample of the project is necessary to get the space for further processing (either getting non-indexed samples or creating them)

2023-03-16 14:21 UTC, wow-such-code commented on drop-boxes/register-attachments-dropbox/register-attachment-dropbox.py
> +			infoSampleID = "/"+space+"/"+code+"000"
this was actually wrong, since the "000" is contained in the code in this case. which makes it even shorter, so IMHO no separate method is needed

2023-03-16 14:21 UTC, wow-such-code commented on drop-boxes/register-attachments-dropbox/register-attachment-dropbox.py
> +				experimentID = '/' + space + '/' + project + '/'+ project+'_INFO'
good point

2023-03-16 16:37 UTC, Steffengreiner submitted a review, later dismissed
Nicely Done! 🚀

2023-03-16 16:37 UTC, Steffengreiner commented on drop-boxes/register-attachments-dropbox/register-attachment-dropbox.py
> +			sc.addMatchClause(SearchCriteria.MatchClause.createAttributeMatch(SearchCriteria.MatchClauseAttribute.CODE, project+"ENTITY-1"))
Ah that makes sense, thanks for the explanation! This could also be moved into a dedicated variable or method name then. But I'd argue that we need to move all the openBis nomenclature into an enum or something at some point down the line 😓

2023-03-16 16:37 UTC, Steffengreiner commented on drop-boxes/register-attachments-dropbox/register-attachment-dropbox.py
> +				sa = transaction.createNewSample(infoSampleID, "Q_ATTACHMENT_SAMPLE")
I agree 👍

2023-03-17 13:44 UTC, Steffengreiner approved these changes
Thanks for clarifing the imports 🙏

2023-03-17 13:45 UTC, merged